# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &CentralGovernment
        Name: CentralGovernmentMSP
        ID: CentralGovernmentMSP
        MSPDir: crypto-config/peerOrganizations/centralgovernment.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CentralGovernmentMSP.admin', 'CentralGovernmentMSP.peer', 'ManufacturerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CentralGovernmentMSP.admin', 'CentralGovernmentMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CentralGovernmentMSP.admin')"
                
    - &StateGovernmentDepot
        Name: StateGovernmentDepotMSP
        ID: StateGovernmentDepotMSP
        MSPDir: crypto-config/peerOrganizations/stategovernmentdepot.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('StateGovernmentDepotMSP.admin', 'StateGovernmentDepotMSP.peer', 'StateGovernmentDepotMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('StateGovernmentDepotMSP.admin', 'StateGovernmentDepotMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('StateGovernmentDepotMSP.admin')"
                
    - &StateGovernmentFPS
        Name: StateGovernmentFPSMSP
        ID: StateGovernmentFPSMSP
        MSPDir: crypto-config/peerOrganizations/stategovernmentfps.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('StateGovernmentFPSMSP.admin', 'StateGovernmentFPSMSP.peer', 'StateGovernmentFPSMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('StateGovernmentFPSMSP.admin', 'StateGovernmentFPSMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('StateGovernmentFPSMSP.admin')"

    - &Other
        Name: OtherMSP
        ID: OtherMSP
        MSPDir: crypto-config/peerOrganizations/other.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OtherMSP.admin', 'OtherMSP.peer', 'OtherMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OtherMSP.admin', 'OtherMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OtherMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    SupplyOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *CentralGovernment
                    - *StateGovernmentDepot
                    - *StateGovernmentFPS
                    - *Other
    SupplyChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *CentralGovernment
                - *StateGovernmentDepot
                - *StateGovernmentFPS
                - *Other
            Capabilities:
                <<: *ApplicationCapabilities

