OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: CentralGovernment
    Domain: centralgovernment.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: StateGovernmentDepot
    Domain: stategovernmentdepot.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: StateGovernmentFPS
    Domain: stategovernmentfps.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Other
    Domain: other.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
