OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: CentralGovernment
    Domain: centralgovernment.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Depots
    Domain: depots.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: FPS
    Domain: fps.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1