# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.centralgovernment.example.com:
  peer0.stategovernmentdepot.example.com:
  peer0.stategovernmentfps.example.com:
  peer0.other.example.com:
  caCentralGovernment:
  caStateGovernmentDepot:
  caStateGovernmentFPS:
  caOther:

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.centralgovernment.example.com:
    container_name: peer0.centralgovernment.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.centralgovernment.example.com
    networks:
      - byfn
      
  peer0.stategovernmentdepot.example.com:
    container_name: peer0.stategovernmentdepot.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.stategovernmentdepot.example.com
    networks:
      - byfn
      
  peer0.stategovernmentfps.example.com:
    container_name: peer0.stategovernmentfps.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.stategovernmentfps.example.com
    networks:
      - byfn
      
  peer0.other.example.com:
    container_name: peer0.other.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.other.example.com
    networks:
      - byfn
       
  caCentralGovernment:
    container_name: caCentralGovernment
    extends:
      file:  base/docker-compose-base.yaml
      service: caCentralGovernment
    networks:
      - byfn
      
  caStateGovernmentDepot:
    container_name: caStateGovernmentDepot
    extends:
      file:  base/docker-compose-base.yaml
      service: caStateGovernmentDepot
    networks:
      - byfn
      
  caStateGovernmentFPS:
    container_name: caStateGovernmentFPS
    extends:
      file:  base/docker-compose-base.yaml
      service: caStateGovernmentFPS
    networks:
      - byfn

  caOther:
    container_name: caOther
    extends:
      file:  base/docker-compose-base.yaml
      service: caOther
    networks:
      - byfn      
      
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.centralgovernment.example.com:7051
      - CORE_PEER_LOCALMSPID=CentralGovernmentMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralgovernment.example.com/peers/peer0.centralgovernment.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralgovernment.example.com/peers/peer0.centralgovernment.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralgovernment.example.com/peers/peer0.centralgovernment.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralgovernment.example.com/users/Admin@centralgovernment.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.centralgovernment.example.com
      - peer0.stategovernmentdepot.example.com
      - peer0.stategovernmentfps.example.com
      - peer0.other.example.com
      - caCentralGovernment
      - caStateGovernmentDepot
      - caStateGovernmentFPS
      - caOther
    networks:
      - byfn
